### ISSUE TITLE
Module-1 Documentation review

### ISSUE THREAD

**Issue by amalik99** [SpektraSystems/Azure-MySQL-DMS-Lab#3]
1. As soon as we login, show both RG screenshot and give their description 
 
2. Please ensure to enter a unique name for storage account name and share name.  >> highlight unique name, storage account name, share name with bold

3. az mysql server create --resource-group <resource-group-name> --sku-name GP_Gen5_8 --name <server name> --location <location> --admin-user mysqlAdminUser --admin-password 'mysqlAdminPassw0rd!' --ssl-enforcement Disabled --storage-size 51200  << Change password to 'Password!1234'

4. When creating mysql server, it kept on running forever for me. Had to create using Portal

4.az webapp deployment user set --user-name "username" --password gitDeployPassw0rd!  >> The publishing username has to be globally unique, and the name you provided has already been taken by another Azure customer. Please type in a different name. >> Tell this

5. git remote add website > ask them to copy URL from output of az web app create  "deploymentLocalGitUrl": "https://holuser198@mysqlamit12.scm.azurewebsites.net/mysqlamit12.git",

6.Open the web site.
14.	The website should be up and running. >> show how to open website and sucessful page

7. Include instruction after creating MySQL Server that ensure SSL is disabled.

8.

**Comment by ShivaniThadiyan** [comment]
Completed.
