### ISSUE TITLE
Module2- Documentation review

### ISSUE THREAD

**Issue by amalik99** [SpektraSystems/Azure-MySQL-DMS-Lab#4]
1. Exercise 1 and 2 - Look for module 1 review
2. mysqldump -h 52.167.5.121 -u root -p --databases sakila > C:\DMS\sakila-mv-data.sql < Change this to localhost from IP
3. mysql.exe -h mydemoservernm.mysql.database.azure.com -u myadmin@mydemoservernm -p sakila > C:\DMS\sakila-mv-data.sql >> don't use .exe. keep same everywhere.

4. mysqldump -h 52.167.5.121 -u root -p --databases sakila > C:\DMS\sakila-mv-data.sql >> this is wrong. we need to add --no-data to command and --database. for example
mysqldump -h localhost -u root -p --databases sakila --no-data > C:\DMS\sakila-mv-data.sql 

5. import schema, it needs to be < instead of >

4. Source server name: localhost under migration task craete - this can not be localhost. this has to be DNS name of the DMS-DeV VM

5. Show cutover step and cutover completed

**Comment by ShivaniThadiyan** [comment]
Completed
